language: java
jdk:
  - oraclejdk8
services:
  - redis-server
install:
  - "wget http://download.redis.io/releases/redis-3.0.6.tar.gz"
  - "tar xzf redis-3.0.6.tar.gz"
  - "cd redis-3.0.6"
  - "make"
  - "src/redis-server --port 6380 --daemonize yes"
  - "cd .."
script:
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
  - mvn test -B